[keybinds]

# Applications and session
"Mod+Return" = { action = "spawn:kitty", repeat = false }
"Mod+U" = "spawn:noctalia msg panel-toggle launcher"
"Mod+Q" = { action = "window-close", repeat = false }
"Mod+Escape" = "session-quit"
"Mod+Shift+Escape" = { action = "shortcuts-inhibit-toggle", allow_when_inhibited = true, repeat = false }
"Mod+Shift+W" = "spawn:noctalia msg plugin yngwe/wallpaperCarousel:service all toggle"
"Mod+Minus" = "spawn:noctalia msg plugin alexander/screen-toolkit:service all recordFullscreenMp4"
"Mod+Shift+Minus" = "spawn:noctalia msg plugin alexander/screen-toolkit:service all recordStop"
"Mod+E" = { action = "spawn:dolphin", repeat = false}
"Mod+B" = { action = "spawn:google-chrome-stable", repeat = false}
"Mod+Z" = { action = "spawn:zeditor", repeat = false}
"Mod+D" = { action = "spawn:dolphin", repeat = false}


# Focus and movement
"Mod+Left" = "window-focus-left"
"Mod+Down" = "window-focus-down"
"Mod+Up" = "window-focus-up"
"Mod+Right" = "window-focus-right"
"Mod+H" = "window-focus-left"
"Mod+J" = "window-focus-down"
"Mod+K" = "window-focus-up"
"Mod+L" = "window-focus-right"
"Mod+F1" = "window-focus-next"
"Mod+Shift+Left" = "column-move-left"
"Mod+Shift+Down" = "window-move-down"
"Mod+Shift+Up" = "window-move-up"
"Mod+Shift+Right" = "column-move-right"


# Window state and layout
"Mod+T" = { action = "window-toggle-floating", repeat = false }
"Mod+Shift+T" = { action = "window-focus-switch-floating", repeat = false }
"Mod+P" = { action = "window-toggle-pinned", repeat = false }
"Mod+F" = { action = "window-toggle-maximize-to-edges", repeat = false }
"Mod+SHIFT+F" = { action = "window-toggle-fullscreen", repeat = false }
"Mod+Ctrl+F" = { action = "window-toggle-maximize", repeat = false }
"Mod+R" = "window-cycle-primary-extent"
"Mod+Shift+R" = "window-cycle-primary-extent-back"
"Mod+Comma" = "window-consume-left"
"Mod+Period" = "window-consume-right"
"Mod+WheelUp" = "window-focus-left"
"Mod+WheelDown" = "window-focus-right"
"Mod+O" = { action = "overview-toggle", repeat = false }

# Workspaces
"Mod+1" = "workspace-switch:1"
"Mod+2" = "workspace-switch:2"
"Mod+3" = "workspace-switch:3"
"Mod+4" = "workspace-switch:4"
"Mod+5" = "workspace-switch:5"
"Mod+6" = "workspace-switch:6"
"Mod+7" = "workspace-switch:7"
"Mod+8" = "workspace-switch:8"
"Mod+9" = "workspace-switch:9"
"Mod+Shift+1" = "window-move-to-workspace:1"
"Mod+Shift+2" = "window-move-to-workspace:2"
"Mod+Shift+3" = "window-move-to-workspace:3"
"Mod+Shift+4" = "window-move-to-workspace:4"
"Mod+Shift+5" = "window-move-to-workspace:5"
"Mod+Shift+6" = "window-move-to-workspace:6"
"Mod+Shift+7" = "window-move-to-workspace:7"
"Mod+Shift+8" = "window-move-to-workspace:8"
"Mod+Shift+9" = "window-move-to-workspace:9"

# Scratchpad
"Mod+Shift+Space" = { action = "window-move-to-scratchpad", repeat = false }
"Mod+Space" = "scratchpad-toggle"
"Mod+Ctrl+Space" = { action = "window-restore-from-scratchpad", repeat = false }
"Mod+Tab" = "scratchpad-focus-next"
