[colors]
background = "#eeeeeeFF"
text_primary = "#1b1b1bFF"
text_muted = "#474747FF"
accent_primary = "#006686FF"
accent_secondary = "#4d616cFF"
warning = "#5e5a7dFF"
error = "#ba1a1aFF"
insert_hint = "#5e5a7d80"
backdrop = "#e2e2e2FF"

[colors.border]
focused = "#006686FF"
unfocused = "#e2e2e2FF"
outer = "#f9f9f9FF"

[colors.overview]
background_tint = "#f9f9f988"
badge = "#006686FF"
workspace_background = "#f9f9f9FF"

[[window_rule]]
match.is_scratchpad = true
border_color_focused = "#5e5a7dFF"
border_color_unfocused = "#e4dfffFF"
